// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7nq6hfngXtkxvzkFy_Lwt5mblhSuPnsQ',
    appId: '1:860530163369:web:3efd41353f53a355ce33b8',
    messagingSenderId: '860530163369',
    projectId: 'adv-software',
    authDomain: 'adv-software.firebaseapp.com',
    storageBucket: 'adv-software.appspot.com',
    measurementId: 'G-C595CXX6H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLKMeGM159tvFooMdc7osX3SGbkHI0-wY',
    appId: '1:860530163369:android:12099bd57c08b338ce33b8',
    messagingSenderId: '860530163369',
    projectId: 'adv-software',
    storageBucket: 'adv-software.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLXCAwMJkzDfftHSYncanAR_w8CVQaeJo',
    appId: '1:860530163369:ios:937f74e63e18b52dce33b8',
    messagingSenderId: '860530163369',
    projectId: 'adv-software',
    storageBucket: 'adv-software.appspot.com',
    iosBundleId: 'com.example.uniVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLXCAwMJkzDfftHSYncanAR_w8CVQaeJo',
    appId: '1:860530163369:ios:63f3a0f07df6ed30ce33b8',
    messagingSenderId: '860530163369',
    projectId: 'adv-software',
    storageBucket: 'adv-software.appspot.com',
    iosBundleId: 'com.example.uniVerse.RunnerTests',
  );
}
